-- MySQL Script generated by MySQL Workbench
-- Tue Feb  5 20:33:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema csce464onlinemoviesdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csce464onlinemoviesdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aschlichtm` DEFAULT CHARACTER SET utf8mb4 ;
USE `aschlichtm` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `State` VARCHAR(45) NULL DEFAULT NULL,
  `PostalCode` VARCHAR(45) NULL DEFAULT NULL,
  `EmailAddress` VARCHAR(45) NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(45) NULL DEFAULT NULL,
  `Birthday` VARCHAR(45) NULL DEFAULT NULL,
  `Type` TINYINT(1) NULL DEFAULT NULL,
  `Status` TINYINT(1) NULL DEFAULT NULL,
  `NumOfVisits` INT(4) NULL DEFAULT NULL,
  `Username` VARCHAR(255) NULL DEFAULT NULL,
  `Password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
INSERT INTO users (FirstName, LastName, Address, City, State, PostalCode, EmailAddress, PhoneNumber, Birthday, Username, Password)
VALUES ('Adam', 'Schlichtmann', '3424 A ST', 'Lincoln', 'Nebraska', '68504', 'adam.schlichtmann1113@gmail.com', '701-245-1234', '12-14-1997', 'adam', 'asdf');
INSERT INTO users (FirstName, LastName, Address, City, State, PostalCode, EmailAddress, PhoneNumber, Birthday, Username, Password)
VALUES ('Adrian', 'Ariffin', '1234 Z ST', 'Lincoln', 'Nebraska', '68507', 'adrian@gmail.com', '701-456-6723', '9-12-1996', 'adrian', 'asdf');

-- -----------------------------------------------------
-- Table `creditcards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creditcards` ;

CREATE TABLE IF NOT EXISTS `creditcards` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `CardHolderName` VARCHAR(255) NULL DEFAULT NULL,
  `CreditCardNumber` CHAR(20) NOT NULL,
  `Balance` DECIMAL(16,2) NULL DEFAULT NULL,
  `CardType` VARCHAR(45) NULL DEFAULT NULL,
  `UserId` INT(11) NULL DEFAULT NULL,
  `CVV` CHAR(4) NULL DEFAULT NULL,
  `ExpirationDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CreditCardNumber` (`CreditCardNumber` ASC),
  INDEX `UserId` (`UserId` ASC),
  CONSTRAINT `creditcards_ibfk_1`
    FOREIGN KEY (`UserId`)
    REFERENCES `users` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
INSERT INTO creditcards (CardHolderName, CreditCardNumber, Balance, CardType, UserId, CVV, ExpirationDate)
VALUES ('Adam Schlichtmann', '6011000200010000', 123410.23, 'Discover', 1, '999', '2029-01-01 01:00:00');
INSERT INTO creditcards (CardHolderName, CreditCardNumber, Balance, CardType, UserId, CVV, ExpirationDate)
VALUES ('Adrian Reza', '1000000200010000', 155023.10, 'MasterCard', '2', '123', '2025-09-01 01:00:00');
-- -----------------------------------------------------
-- Table `concert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concert` ;

CREATE TABLE IF NOT EXISTS `concert` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ConcertName` VARCHAR(45) NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `Thumbnail` BLOB NULL DEFAULT NULL,
  `Rating` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
INSERT INTO concert (ConcertName, Description, Rating, Thumbnail)
VALUES ('Logic', 'Join Logic on his Bobby Tarintino II tour!', '4', '../WebContent/Pics/Logic.jpeg'); 
INSERT INTO concert (ConcertName, Description, Rating, Thumbnail)
VALUES ('Chance The Rapper', 'Join Chance on his new Tour!','5', '../WebContent/Pics/Chance.jpg'); 
INSERT INTO concert (ConcertName, Description, Rating, Thumbnail)
VALUES ('Kyd the Band', 'Join Kyd the Band on their first tour!', '4', '../WebContent/Pics/KydTheBand.jpg'); 

-- -----------------------------------------------------
-- Table `venue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venue` ;

CREATE TABLE IF NOT EXISTS `venue` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `ownerID` INT NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `PostalCode` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `ownerID_idx` (`ownerID` ASC),
  CONSTRAINT `ownerID_venue`
    FOREIGN KEY (`ownerID`)
    REFERENCES `users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
INSERT INTO venue (Name, Address, City, State, PostalCode)
VALUES ('Bourbon Theater', '1345 O St', 'Lincoln', 'Nebraska', '68510');
INSERT INTO venue (Name, Address, City, State, PostalCode)
VALUES ('Pinnacle Band Arena', '900 R St', 'Lincoln', 'Nebraska', '68510');
INSERT INTO venue (Name, Address, City, State, PostalCode)
VALUES ('FargoDome', '1900 University DR', 'Fargo', 'North Dakota', '58106');
INSERT INTO venue (Name, Address, City, State, PostalCode)
VALUES ('Scheels Arena', '4210 Vertrans Dr', 'Fargo', 'North Dakota', '58104');



-- -----------------------------------------------------
-- Table `performance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `performance` ;

CREATE TABLE IF NOT EXISTS `performance` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `StartTime` DATETIME NULL DEFAULT NULL,
  `EndTime` DATETIME NULL DEFAULT NULL,
  `concertID` INT NULL,
  `venueID` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `performanceID_idx` (`concertID` ASC),
  INDEX `venueID_idx` (`venueID` ASC),
  CONSTRAINT `concertID_perf`
    FOREIGN KEY (`concertID`)
    REFERENCES `concert` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `venueID_perf`
    FOREIGN KEY (`venueID`)
    REFERENCES `venue` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2019-04-23 07:00:00', '2019-04-23 10:00:00', 1, 1);
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2019-09-12 05:00:00', '2019-09-12 07:00:00', 2, 1);
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2019-05-15 07:00:00', '2019-05-15 10:00:00', 3, 1);
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2020-01-23 07:00:00', '2020-01-23 10:00:00', 1, 2);
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2019-08-17 05:00:00', '2019-08-17 07:00:00', 2, 2);
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2019-07-05 07:00:00', '2019-07-05 10:00:00', 3, 2);
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2020-03-14 07:00:00', '2020-03-14 10:00:00', 1, 3);
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2019-10-14 05:00:00', '2019-10-14 07:00:00', 2, 3);
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2019-11-08 07:00:00', '2019-11-08 10:00:00', 3, 3);
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2020-05-01 07:00:00', '2020-05-01 10:00:00', 1, 4);
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2019-03-28 05:00:00', '2019-03-28 07:00:00', 2, 4);
INSERT INTO performance (StartTime, EndTime, concertID, venueID)
VALUES ('2019-08-05 07:00:00', '2019-08-05 10:00:00', 3, 4);

-- -----------------------------------------------------
-- Table `customerreviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customerreviews` ;

CREATE TABLE IF NOT EXISTS `customerreviews` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `concertID` INT(11) NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  `ReviewDate` VARCHAR(40) NULL DEFAULT NULL,
  `Rating` TINYINT(1) NULL DEFAULT NULL,
  `Review` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `concertID` (`concertID` ASC),
  INDEX `UserId` (`userID` ASC),
  CONSTRAINT `concertID_cr`
    FOREIGN KEY (`concertID`)
    REFERENCES `concert` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userID_cr`
    FOREIGN KEY (`userID`)
    REFERENCES `users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
INSERT INTO customerreviews (concertID, userID, ReviewDate, Rating, Review)
VALUES (1, 1, '2018-03-09 10:22:00', 5, "Great Concert Would love to go again!");
INSERT INTO customerreviews (concertID, userID, ReviewDate, Rating, Review)
VALUES (2, 2, '2019-01-20 12:45:00', 4, "Good concert wish it would have been longer!");
INSERT INTO customerreviews (concertID, userID, ReviewDate, Rating, Review)
VALUES (3, 1, '2018-03-29 8:45:00', 5, "These guys are going to be huge this year!");


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `CustomerId` INT(11) NULL DEFAULT NULL,
  `TotalCost` INT(11) NULL DEFAULT NULL,
  `OrderDate` VARCHAR(40) NULL DEFAULT NULL,
  `BillingAddress` VARCHAR(255) NULL DEFAULT NULL,
  `CreditCardNumber` CHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `CustomerId` (`CustomerId` ASC),
  CONSTRAINT `CustomerID_orders`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
INSERT INTO orders (CustomerId, TotalCost, OrderDate, BillingAddress, CreditCardNumber)
VALUES (2, 75, '2018-03-29 12:45:00', "123 A St Lincoln NE", 1000000200010000);
INSERT INTO orders (CustomerId, TotalCost, OrderDate, BillingAddress, CreditCardNumber)
VALUES (1, 105, '2019-01-29 8:45:00', "412 Leigton AVE, Lincoln NE", 6011000200010000);
INSERT INTO orders (CustomerId, TotalCost, OrderDate, BillingAddress, CreditCardNumber)
VALUES (2, 75, '2018-011-20 10:00:00', "123 A St Lincoln NE", 1000000200010000);


-- -----------------------------------------------------
-- Table `orderitems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orderitems` ;

CREATE TABLE IF NOT EXISTS `orderitems` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `OrderId` INT(11) NULL DEFAULT NULL,
  `PerformanceID` INT(11) NULL DEFAULT NULL,
  `Quantity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `OrderId` (`OrderId` ASC),
  INDEX `ProductId` (`PerformanceID` ASC),
  CONSTRAINT `performanceID_orderitem`
    FOREIGN KEY (`PerformanceID`)
    REFERENCES `performance` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrderID_orderitem`
    FOREIGN KEY (`OrderId`)
    REFERENCES `orders` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
INSERT INTO orderitems (OrderId, PerformanceID, Quantity)
VALUES (1, 2, 3);
INSERT INTO orderitems (OrderId, PerformanceID, Quantity)
VALUES (2, 5, 3);
INSERT INTO orderitems (OrderId, PerformanceID, Quantity)
VALUES (3, 1, 2);


-- -----------------------------------------------------
-- Table `Ticket Types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tickettypes` ;

CREATE TABLE IF NOT EXISTS `tickettypes` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `SeatName` VARCHAR(45) NULL,
  `Ticket` VARCHAR(45) NULL,
  PRIMARY KEY (`idTicket`))
ENGINE = InnoDB;
INSERT INTO tickettypes (SeatName, Ticket)
VALUES ("General Admission Floor", NULL);
INSERT INTO tickettypes (SeatName, Ticket)
VALUES ("Reserved Seating", NULL);

-- -----------------------------------------------------
-- Table `TicketVenuePrices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TicketVenuePrices` ;

CREATE TABLE IF NOT EXISTS `TicketVenuePrices` (
  `idTicketVenuePrices` INT NOT NULL AUTO_INCREMENT,
  `TicketPrice` INT NULL,
  `venueID` INT NULL,
  `ticketTypeID` INT NULL,
  `performanceID` INT NULL,
  PRIMARY KEY (`idTicketVenuePrices`),
  INDEX `TicketTypeID_idx` (`ticketTypeID` ASC),
  INDEX `VenueID_idx` (`venueID` ASC),
  INDEX `PerformanceID_idx` (`performanceID` ASC),
  CONSTRAINT `TicketTypeID_tick`
    FOREIGN KEY (`ticketTypeID`)
    REFERENCES `tickettypes` (`idTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VenueID_tick`
    FOREIGN KEY (`venueID`)
    REFERENCES `venue` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PerformanceID_tick`
    FOREIGN KEY (`performanceID`)
    REFERENCES `performance` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 1, 1, 1);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 1, 2, 1);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 1, 1, 2);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 1, 2, 2);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 1, 1, 3);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 1, 2, 3);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 1, 1, 4);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 1, 2, 4);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 1, 1, 1);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 1, 2, 1);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 2, 1, 2);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 2, 2, 2);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 2, 1, 3);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 2, 2, 3);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 2, 1, 4);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 2, 2, 4);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 3, 1, 1);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 3, 2, 1);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 3, 1, 2);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 3, 2, 2);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 3, 1, 3);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 3, 2, 3);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 3, 1, 4);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 3, 2, 4);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 4, 1, 1);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 4, 2, 1);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 4, 1, 2);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 4, 2, 2);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 4, 1, 3);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 4, 2, 3);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (50, 4, 1, 4);
INSERT INTO TicketVenuePrices (TicketPrice, venueID, ticketTypeID, performanceID)
VALUES (80, 4, 2, 4);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
